-- Managing club_roles (positions) is now possible from the Attributes
-- admin UI (executives can add new positions as the club grows/
-- restructures, i.e. 増設). club_roles.id was originally a plain smallint
-- PK with all 14 rows seeded explicitly by id (0001_club_roles.sql) and no
-- default -- fine when rows were only ever inserted by migration, but the
-- new UI needs the database to allocate new ids safely (including under
-- concurrent inserts) rather than the client computing max(id)+1 itself.
--
-- Add an identity-backed default, restarting after the highest existing
-- seeded id (14) so newly-generated ids can't collide with any seeded row.
alter table club_roles alter column id add generated by default as identity;
alter table club_roles alter column id restart with 15;
